import type {NextPage} from "next";

import Head from "next/head";

import {
  useAddPointsMutation,
  useGetHistoryQuery,
  useGetProductsQuery,
  useGetUserQuery,
  useRedeemMutation,
} from "@redux/features/products/productsApiSlice";
import {AddPoints, Redeem} from "@types";
import Navbar from "@components/navbar";
import Products from "@components/products";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  // const {data = [], isFetching} = useGetProductsQuery();
  const {data: user, refetch} = useGetUserQuery();

  const [addPoints] = useAddPointsMutation();
  const handleAddPoints = async (amount: AddPoints) => {
    await addPoints(amount);
    refetch();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        {`<Navbar/>`}
        {`<BackgroundWave>`}
        {`<Hero />`}
        {`<Walkthrough>`}
        {`<BackgroundWave/>`}
        {`<Products />`}
        {`<Footer />`}
        <button onClick={() => handleAddPoints({amount: 1000})}>Aumentar 1000 puntos</button>
        <button onClick={() => handleAddPoints({amount: 5000})}>Aumentar 5000 puntos</button>
        <button onClick={() => handleAddPoints({amount: 7500})}>Aumentar 7500 puntos</button>
        <p>{user?.name}</p>
        <p>${user?.points}</p>
        <Products />
      </main>
    </div>
  );
};

export default Home;
